//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCWebAPIProducts.Entities.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Precios
    {
        public int Id { get; set; }
        public System.DateTime FAlta { get; set; }
        public Nullable<System.DateTime> FBaja { get; set; }
        public int ProductoId { get; set; }
        public Nullable<decimal> Utilidad { get; set; }
        public decimal PrecioVenta { get; set; }
        public Nullable<decimal> Tarjeta { get; set; }
    
        public virtual Productos Productos { get; set; }
    }
}
