//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCWebAPIProducts.Entities.Model
{
  using System.Data.Entity;
  using System.Data.Entity.Infrastructure;

  public partial class SiSistemasDEMOEntities : DbContext
  {
    public SiSistemasDEMOEntities(string connString)
    : base(connString)
    {
    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
      throw new UnintentionalCodeFirstException();
    }

    public virtual DbSet<Precios> Precios { get; set; }
    public virtual DbSet<Productos> Productos { get; set; }
  }
}
