//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCWebAPIProducts.Models
{
    using System;
  using System.Configuration;
  using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
  using System.Data.SqlClient;
  //using Microsoft.Configuration.ConfigurationBuilders.AzureAppConfiguration;
  //using Microsoft.Configuration.ConfigurationBuilders.Environment;
  //using System.Configuration.ConfigurationManager;

  public partial class SiSistemasWebEntities : DbContext
    {
        public SiSistemasWebEntities()
            : base("name=SiSistemasWebEntities")

   // :base(Configuration.Get("Data:DefaultConnection:ConnectionString"))
            //: base((new SqlConnectionStringBuilder(
              
            //CloudConfigurationManager.GetSetting("dbRAActivity")).ToString()))
        {
    //  Configuration.Get("Data:DefaultConnection:ConnectionString");

        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }

    
    //protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    //{
    //  optionsBuilder.UseSqlServer(ConfigurationManager.ConnectionStrings["BloggingDatabase"].ConnectionString);
    //}

    public virtual DbSet<Precios> Precios { get; set; }
        public virtual DbSet<Productos> Productos { get; set; }
        public virtual DbSet<Usuarios> Usuarios { get; set; }
    }
}
